/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CK_JAVA;


/**
 *
 * @author ADMIN
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    public DangNhap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_28 = new javax.swing.JPanel();
        jPanel3_28 = new javax.swing.JPanel();
        txtUserName_28 = new javax.swing.JTextField();
        txtPassWord_28 = new javax.swing.JPasswordField();
        jSeparator_28 = new javax.swing.JSeparator();
        jjSeparator_28 = new javax.swing.JSeparator();
        iconKey_28 = new javax.swing.JLabel();
        btnSignUp_28 = new javax.swing.JButton();
        btnSignin_28 = new javax.swing.JButton();
        iconUser_28 = new javax.swing.JLabel();
        lbJavaHome_28 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3_28.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3_28.setForeground(new java.awt.Color(255, 51, 153));
        jPanel3_28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName_28.setBackground(new java.awt.Color(153, 255, 255));
        txtUserName_28.setBorder(null);
        txtUserName_28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserName_28ActionPerformed(evt);
            }
        });
        jPanel3_28.add(txtUserName_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 200, 30));

        txtPassWord_28.setBackground(new java.awt.Color(153, 255, 255));
        txtPassWord_28.setBorder(null);
        jPanel3_28.add(txtPassWord_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 30));

        jSeparator_28.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3_28.add(jSeparator_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 200, 20));

        jjSeparator_28.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3_28.add(jjSeparator_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 200, 10));

        iconKey_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_lock_20px.png"))); // NOI18N
        jPanel3_28.add(iconKey_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 20, 30));

        btnSignUp_28.setBackground(new java.awt.Color(255, 255, 255));
        btnSignUp_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_Close_20px.png"))); // NOI18N
        btnSignUp_28.setText("Thoát");
        btnSignUp_28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUp_28ActionPerformed(evt);
            }
        });
        jPanel3_28.add(btnSignUp_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        btnSignin_28.setBackground(new java.awt.Color(255, 255, 255));
        btnSignin_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_workspace_20px.png"))); // NOI18N
        btnSignin_28.setText("Đăng Nhập");
        btnSignin_28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignin_28ActionPerformed(evt);
            }
        });
        jPanel3_28.add(btnSignin_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        iconUser_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_user_20px_2.png"))); // NOI18N
        jPanel3_28.add(iconUser_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 20, 20));

        lbJavaHome_28.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbJavaHome_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_3d_printer_75px.png"))); // NOI18N
        lbJavaHome_28.setText("LOGIN");
        jPanel3_28.add(lbJavaHome_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setText("Chức Vụ:");
        jPanel3_28.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân Viên", "Chủ " }));
        jPanel3_28.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 80, -1));

        javax.swing.GroupLayout jPanel1_28Layout = new javax.swing.GroupLayout(jPanel1_28);
        jPanel1_28.setLayout(jPanel1_28Layout);
        jPanel1_28Layout.setHorizontalGroup(
            jPanel1_28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_28Layout.createSequentialGroup()
                .addComponent(jPanel3_28, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1_28Layout.setVerticalGroup(
            jPanel1_28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_28Layout.createSequentialGroup()
                .addComponent(jPanel3_28, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUp_28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUp_28ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUp_28ActionPerformed

    private void txtUserName_28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserName_28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserName_28ActionPerformed

    private void btnSignin_28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignin_28ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_btnSignin_28ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp_28;
    private javax.swing.JButton btnSignin_28;
    private javax.swing.JLabel iconKey_28;
    private javax.swing.JLabel iconUser_28;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1_28;
    private javax.swing.JPanel jPanel3_28;
    private javax.swing.JSeparator jSeparator_28;
    private javax.swing.JSeparator jjSeparator_28;
    private javax.swing.JLabel lbJavaHome_28;
    private javax.swing.JPasswordField txtPassWord_28;
    private javax.swing.JTextField txtUserName_28;
    // End of variables declaration//GEN-END:variables
}
