/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CK_JAVA;

/**
 *
 * @author ADMIN
 */
public class QLLinhKien extends javax.swing.JFrame {

    /**
     * Creates new form TEst
     */
    public QLLinhKien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbMalinhkien_28 = new javax.swing.JLabel();
        lbTenlinhkien_28 = new javax.swing.JLabel();
        lbLoailinhkien_28 = new javax.swing.JLabel();
        txtTenlinhkien = new javax.swing.JTextField();
        txtMalinhkien = new javax.swing.JTextField();
        cbLoailinhkien_28 = new javax.swing.JComboBox<>();
        lbGia_28 = new javax.swing.JLabel();
        txtGia_28 = new javax.swing.JTextField();
        lbSoLuong_28 = new javax.swing.JLabel();
        lbMansx_28 = new javax.swing.JLabel();
        txtSoluong_28 = new javax.swing.JTextField();
        cbMansx_28 = new javax.swing.JComboBox<>();
        btnThem_28 = new javax.swing.JButton();
        btnSua_28 = new javax.swing.JButton();
        btnXoa_28 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLinhkien_28 = new javax.swing.JTable();
        btnLammoi_28 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Thoatbtn_28 = new javax.swing.JButton();
        Tieude_28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMalinhkien_28.setText("Mã Linh Kiện:");

        lbTenlinhkien_28.setText("Tên Linh Kiện:");

        lbLoailinhkien_28.setText("Loại Linh Kiện:");

        cbLoailinhkien_28.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbGia_28.setText("Giá:");

        lbSoLuong_28.setText("Số Lượng:");

        lbMansx_28.setText("Mã NSX:");

        cbMansx_28.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThem_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_add_20px.png"))); // NOI18N
        btnThem_28.setText("Thêm");

        btnSua_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_computer_support_20px.png"))); // NOI18N
        btnSua_28.setText("Sửa");

        btnXoa_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_Delete_20px.png"))); // NOI18N
        btnXoa_28.setText("Xoá");

        tableLinhkien_28.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Linh Kiện", "Tên Linh Kiện", "Số Lượng", "Loại Linh Kiện", "Giá", "Mã NSX"
            }
        ));
        jScrollPane1.setViewportView(tableLinhkien_28);

        btnLammoi_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_refresh_20px.png"))); // NOI18N
        btnLammoi_28.setText("Làm Mới");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnLammoi_28)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbGia_28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbTenlinhkien_28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenlinhkien)
                                    .addComponent(txtGia_28, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                .addGap(37, 37, 37))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem_28)
                                .addGap(80, 80, 80)
                                .addComponent(btnSua_28)
                                .addGap(51, 51, 51)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbSoLuong_28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbMansx_28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoluong_28)
                                    .addComponent(cbMansx_28, 0, 104, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnXoa_28))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbMalinhkien_28)
                                .addGap(18, 18, 18)
                                .addComponent(txtMalinhkien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbLoailinhkien_28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbLoailinhkien_28, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbMalinhkien_28))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMalinhkien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTenlinhkien_28)
                        .addComponent(txtTenlinhkien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbSoLuong_28)
                        .addComponent(txtSoluong_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbLoailinhkien_28)
                            .addComponent(cbLoailinhkien_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGia_28)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGia_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMansx_28)
                            .addComponent(cbMansx_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem_28)
                    .addComponent(btnXoa_28)
                    .addComponent(btnLammoi_28)
                    .addComponent(btnSua_28))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, 320));

        Thoatbtn_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_logout_rounded_left_20px_1.png"))); // NOI18N
        Thoatbtn_28.setText("THOÁT");
        getContentPane().add(Thoatbtn_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        Tieude_28.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Tieude_28.setText("QUẢN LÝ LINH KIỆN");
        getContentPane().add(Tieude_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 12, 280, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLLinhKien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLLinhKien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLLinhKien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLLinhKien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLLinhKien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Thoatbtn_28;
    private javax.swing.JLabel Tieude_28;
    private javax.swing.JButton btnLammoi_28;
    private javax.swing.JButton btnSua_28;
    private javax.swing.JButton btnThem_28;
    private javax.swing.JButton btnXoa_28;
    private javax.swing.JComboBox<String> cbLoailinhkien_28;
    private javax.swing.JComboBox<String> cbMansx_28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbGia_28;
    private javax.swing.JLabel lbLoailinhkien_28;
    private javax.swing.JLabel lbMalinhkien_28;
    private javax.swing.JLabel lbMansx_28;
    private javax.swing.JLabel lbSoLuong_28;
    private javax.swing.JLabel lbTenlinhkien_28;
    private javax.swing.JTable tableLinhkien_28;
    private javax.swing.JTextField txtGia_28;
    private javax.swing.JTextField txtMalinhkien;
    private javax.swing.JTextField txtSoluong_28;
    private javax.swing.JTextField txtTenlinhkien;
    // End of variables declaration//GEN-END:variables
}
