/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CK_JAVA;

/**
 *
 * @author ADMIN
 */
public class QLNV extends javax.swing.JFrame {

    /**
     * Creates new form TEst
     */
    public QLNV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbManhanvien_28 = new javax.swing.JLabel();
        lbTenNV_28 = new javax.swing.JLabel();
        lbChucvu_28 = new javax.swing.JLabel();
        txtTenNV_28 = new javax.swing.JTextField();
        txtMaNV_28 = new javax.swing.JTextField();
        cbChucvu_28 = new javax.swing.JComboBox<>();
        lbGioitinh_28 = new javax.swing.JLabel();
        lbLuong_28 = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        txtLuong_28 = new javax.swing.JTextField();
        btnCapnhat_28 = new javax.swing.JButton();
        btnSua_28 = new javax.swing.JButton();
        btnXoa_28 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNV_28 = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        rdbNam_28 = new javax.swing.JRadioButton();
        rdbNu_28 = new javax.swing.JRadioButton();
        txtEmail_28 = new javax.swing.JTextField();
        lbSdt_28 = new javax.swing.JLabel();
        txtSdt_28 = new javax.swing.JTextField();
        lbNgaysinh_28 = new javax.swing.JLabel();
        cbNgaysinh_28 = new javax.swing.JComboBox<>();
        btnThoat_28 = new javax.swing.JButton();
        Tieude_28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbManhanvien_28.setText("Mã Nhân Viên:");

        lbTenNV_28.setText("Tên Nhân Viên:");

        lbChucvu_28.setText("Chức Vụ");

        cbChucvu_28.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbGioitinh_28.setText("Giới tính:");

        lbLuong_28.setText("Lương:");

        lbEmail.setText("Email:");

        btnCapnhat_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_add_20px.png"))); // NOI18N
        btnCapnhat_28.setText("Cập Nhật");

        btnSua_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_computer_support_20px.png"))); // NOI18N
        btnSua_28.setText("Sửa");

        btnXoa_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_Delete_20px.png"))); // NOI18N
        btnXoa_28.setText("Xoá");

        tableNV_28.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Chức Vụ", "Lương", "Giới Tính", "Email", "SĐT", "Ngày Sinh"
            }
        ));
        jScrollPane1.setViewportView(tableNV_28);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_refresh_20px.png"))); // NOI18N
        btnRefresh.setText("Refresh");

        rdbNam_28.setText("Nam");

        rdbNu_28.setText("Nữ");

        lbSdt_28.setText("SĐT:");

        lbNgaysinh_28.setText("Ngày Sinh:");

        cbNgaysinh_28.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbManhanvien_28)
                                .addGap(4, 4, 4)
                                .addComponent(txtMaNV_28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbGioitinh_28)
                                .addGap(6, 6, 6)
                                .addComponent(rdbNam_28)
                                .addGap(18, 18, 18)
                                .addComponent(rdbNu_28)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbTenNV_28)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenNV_28, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtEmail_28, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(lbSdt_28))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCapnhat_28)
                                        .addGap(39, 39, 39)
                                        .addComponent(btnSua_28))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnRefresh)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lbChucvu_28)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbChucvu_28, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSdt_28, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbNgaysinh_28)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(lbLuong_28)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLuong_28, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 22, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(cbNgaysinh_28, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnXoa_28)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbManhanvien_28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtMaNV_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbTenNV_28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtTenNV_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbChucvu_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbChucvu_28)
                        .addComponent(lbLuong_28)
                        .addComponent(txtLuong_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbGioitinh_28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(rdbNam_28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbNu_28)
                            .addComponent(lbEmail)
                            .addComponent(txtEmail_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSdt_28)
                            .addComponent(txtSdt_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNgaysinh_28)
                            .addComponent(cbNgaysinh_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapnhat_28)
                    .addComponent(btnRefresh)
                    .addComponent(btnSua_28)
                    .addComponent(btnXoa_28))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, 320));

        btnThoat_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CK_JAVA/icons8_logout_rounded_left_20px_1.png"))); // NOI18N
        btnThoat_28.setText("THOÁT");
        getContentPane().add(btnThoat_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        Tieude_28.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Tieude_28.setText("QUẢN LÝ NHÂN VIÊN");
        getContentPane().add(Tieude_28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 12, 280, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tieude_28;
    private javax.swing.JButton btnCapnhat_28;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua_28;
    private javax.swing.JButton btnThoat_28;
    private javax.swing.JButton btnXoa_28;
    private javax.swing.JComboBox<String> cbChucvu_28;
    private javax.swing.JComboBox<String> cbNgaysinh_28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbChucvu_28;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGioitinh_28;
    private javax.swing.JLabel lbLuong_28;
    private javax.swing.JLabel lbManhanvien_28;
    private javax.swing.JLabel lbNgaysinh_28;
    private javax.swing.JLabel lbSdt_28;
    private javax.swing.JLabel lbTenNV_28;
    private javax.swing.JRadioButton rdbNam_28;
    private javax.swing.JRadioButton rdbNu_28;
    private javax.swing.JTable tableNV_28;
    private javax.swing.JTextField txtEmail_28;
    private javax.swing.JTextField txtLuong_28;
    private javax.swing.JTextField txtMaNV_28;
    private javax.swing.JTextField txtSdt_28;
    private javax.swing.JTextField txtTenNV_28;
    // End of variables declaration//GEN-END:variables
}
